import { ThemeProvider } from '@/providers/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header/header'
import ScrollToTop from '@/components/ScrollToTop'
import Footer from '@/components/Footer'
import { ClerkProvider } from '@clerk/nextjs'
import { ClerkLoaded, ClerkLoading } from '@clerk/nextjs'
import ClerkLoad from '@/components/Loading/ClerkLoad'
import { ToasterProvider } from '@/providers/toast-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">

      <body className="dark:bg-black ">
      <ThemeProvider>
      <ToasterProvider/>
        <ClerkLoading >
          <ClerkLoad/>
    
    
        </ClerkLoading>
        <ClerkLoaded>
     
            <Header/>
            {children}
                
            <Footer />
            <ScrollToTop />
        
        </ClerkLoaded>

      </ThemeProvider>
      </body>

    </html>

    </ClerkProvider>
  )
}
